### ISSUE TITLE
No support for OWASP ZAP

### ISSUE THREAD

**Issue by psiinon** [trustedsec/ptf#154]
Not that I could see anyway :(
Should be easy to include - it just needs Java7 +
Let me know if you need any help including it.

**Comment by trustedsec** [comment]
Would love to add - I'm having a hard time finding a link that grabs the latest version. I see you have an XML that gets updated: https://raw.githubusercontent.com/zaproxy/zap-admin/master/ZapVersions.xml

With the latest version - I would need a link or have to write a customer parser which is a lot more work. Not saying I won't, but if you have a link where we can snag it regularly vs. have to manually update numbers that would be helpful...

**Comment by psiinon** [comment]
You shouldnt need to write a custom parser, its XML, which isnt exactly unusual ;)
What technologies are you happy to use?
For generating our docker images we use xmlstarlet : https://github.com/zaproxy/zaproxy/blob/develop/build/docker/Dockerfile-stable#L13

**Comment by trustedsec** [comment]
The issue isn't how easy XML is to parse - it's what the framework supports. Since this is more of a framework around managing multiple tools - it would require building an additional method for handling updates exclusive to yours. Right now it supports SVN, GIT, and FILE (pull from site). Since this isn't using a standard method, I would need to write another method. The easiest would be to have a link that is something like

github.com/zaproxy/latest.tar.gz - then whenever someone updates they would just pull the latest. Or being able to check it out with git is the best from a source code perspective.

The docker method might be suitable as well - I'll have to take a look at that. We allow something called after_commands which can run that script and use it. Not 100% desirable since it would require those to be executed each time someone wanted to update - the best is through git and being able to build it that way. I'll take a peek regardless when I have some time and find the best method. Appreciate the feedback..

**Comment by trustedsec** [comment]
Done. Added custom parser and works and installs.
