### ISSUE TITLE
Launchers

### ISSUE THREAD

**Issue by pjhartlieb** [trustedsec/ptf#275]
I'm seeing what looks like odd behavior with the launchers?

For example, it looks like john and crunch both contain the launcher flag in the modules themselves.  However,
>john ---> does not launch
>crunch ---> works just fine

Also, 
> which crunch
/usr/bin/crunch
> which hashcat
/usr/local/bin/hashcat

The documents suggest that any launcher created is placed in /usr/local/bin?

**Comment by ccsplit** [comment]
It appears the issue is caused by it attempting to find a launcher within the install location by the name `john`. Which in my latest build at least, the john executable is placed within a run folder under the installation directory. Since it doesn't find the executable it is not creating a launcher for it. The following [method lines](https://github.com/trustedsec/ptf/blob/master/src/core.py#L330-L381) are where the check is being made and if `point` is not `""` it will create the launcher.

**Comment by pjhartlieb** [comment]
excellent ... thanks!
