### ISSUE TITLE
setoolkit LAUNCHER issue

### ISSUE THREAD

**Issue by x653** [trustedsec/ptf#339]
setoolkit needs to be installed in /usr/share/setoolkit, because this path is hardcoded:
for example you find in /pentest/exploitation/setoolkit/src/core/setcore.py (there are other places too)
    def definepath():
        if check_os() == "posix":
            if os.path.isfile("setoolkit"):
                return os.getcwd()
            else:
                return "/usr/share/setoolkit/"
        else:
            return os.getcwd()

I like the Idea of ptf storing all the tools in /pentest.., so I changed the LAUNCHER to

#!/bin/sh
cd /pentest/exploitation/setoolkit/
sudo ./setoolkit

Maybe you can think of introducing a "cd .." command in the LAUNCHER-script?

**Comment by jeffmcjunkin** [comment]
Just chiming in, changing directories is also non-ideal, because most people expect to be able to use local file references when they're calling the launcher (like `setoolkit --profile some_local_file`).

The proper thing is for the upstream utilities to check the directory they're running out of, but not all of ptf's upstream utilities are built that way. Either ptf needs to maintain a patch to each of those utilities (which seems unlikely), or something's gonna break. It can be local file references, or it can be the upstream utilities in some way.

**Comment by x653** [comment]
Maybe its better to change the modules/exploitation/setoolkit.py:

AFTER_COMMANDS="cd {INSTALL_LOCATION},python setup.py install"
LAUNCHER="seproxy"

The setup.py script will copy all files in /usr/share/setoolkit and add a Launcher.

**Comment by coen378** [comment]
Help me.. How to fix 
./ptf
Traceback (most recent call last):
  File "./ptf", line 48, in <module>
    os.makedirs("/usr/local/bin/")
  File "/data/data/com.termux/files/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/data/data/com.termux/files/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/data/data/com.termux/files/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/usr'

**Comment by trustedsec** [comment]
Should be fixed in latest issue as for coen378 - looks like you ran out of memory or don't have write permissions.
