### ISSUE TITLE
zaproxy error

### ISSUE THREAD

**Issue by mother2110** [trustedsec/ptf#473]
When installing I am using 

use modules/install_updates_all

I get the following error..

Installing and/or updating: modules/exploitation/zaproxy
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occurred.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: module 'urllib' has no attribute 'request'

**Comment by redheadedrod** [comment]
Getting same error with latest version of Kali when doing fresh install. Rolling 2019.3
I install zaproxy and rerun and same thing is coming up. 
I am using "The Hackers Playbook 3" setup stuff and this happens with the "use modules/exploitation/install_update_all" command.

**Comment by RedTahr** [comment]
looks like a common issue with urllib
https://stackoverflow.com/questions/22278993/attributeerror-module-object-has-no-attribute-request
i edited src/core.py and added import urllib.request and zaproxy wget is happier this time.
i'm running raspbian (i386 variant) on an atom based netbook.

**Comment by whereistheraper** [comment]
Same as @RedTahr edited src/core.py :` import urllib` to --> `import urllib.request`.
Work on debian10 !

**Comment by ma7amd** [comment]
facing the following error while trying to do a fresh installation on Ubuntu 18.04.3

Installing and/or updating: modules/exploitation/zaproxy
[!] [!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occurred.
[!] [!] It's not possible its due to my coding skillz, it must be you? :-)
[!] [!] Printing that error. Get that error. You get it: module 'urllib' has no attribute 'request'

any help for that error?

**Comment by RedTahr** [comment]
@ma7amd if you read the posts prior to yours you'll see what'll likely fix it for you.
