### ISSUE TITLE
[FEATURE REQUEST] Output Installation/Update of tools to .log file(s)

### ISSUE THREAD

**Issue by 4ndr3w6** [trustedsec/ptf#489]
Installation/Update of tools outputs to a .log file(s) in a directory that can be used to triage install/update problems.

**Comment by jeffmcjunkin** [comment]
You could pipe all the output to `tee` to save the output:
https://github.com/trustedsec/ptf#running-unattended

**Comment by jeffmcjunkin** [comment]
Example for context:
```
./ptf | tee log.txt <<EOF
use modules/exploitation/metasploit
run
use modules/password-recovery/johntheripper
run
EOF
```

**Comment by thejoker3000** [comment]
I'm working on parts of the tool to output the logs as requested (because I have nothing better to do now) and was wondering, should we only log the commands being run or log everything? In my opinion, I think it's best to just log just commands we pass through arguments and such instead of logging everything since that will occupy lots of space more less. But to be hones, the best way for this is to just do what @jeffmcjunkin did in the example above. Any opinions or was this issue supposed to be closed?

**Comment by 4ndr3w6** [comment]
@thejoker3000 My initial thinking behind this was to somehow get an easy way to triage modules that fail to install partially and/or fully. I tried to use CircleCI but had no luck. So I thought having the output of update/install written to a log file for triage as an easier solution. Wondering if it should be broken into 2 flags (i.e. --no-log and --log) that way the operator has the flexibility.

**Comment by thejoker3000** [comment]
Ok. I'm still working on it and trying to make it easier to understand since some of the code is put in different areas of the code (not much) but so far it's working. I've pushed the updates into my repo. but don't want to make the pull request just yet. I would like you guys especially @HackingDave to test it first. I am trying to figure out how to use the config file for logging instead of using a default mode already that is in this part https://github.com/thejoker3000/ptf/blob/master/src/ptflogger.py of the code. Don't know if that makes sense.
Anyways, the code that has the logging is in here -->  https://github.com/thejoker3000/ptf

**Comment by thejoker3000** [comment]
Forgot to mention as well that it is not logging much for the **install** command. Not sure why so don't expect it to log much. When updating on the other hand, it logs the update

**Comment by thejoker3000** [comment]
Update: I've figured out a way to use the **logger** that is already in ptf but it's not working how it should when using the subprocess to install or update.
