### ISSUE TITLE
Cannot handle multi arch download link or file

### ISSUE THREAD

**Issue by samiux** [trustedsec/ptf#56]
It seems PTF only install x86 tools instead of x86_64, for example, HconSTF.  If it can detect multi arch  of the OS, it will be fine.

**Comment by trustedsec** [comment]
Easy to define what platform its using through 

import platform
platform.architecture()

What specifically did you need to do in order to leverage x86/64?

**Comment by samiux** [comment]
For example, according to the contributed module --- https://github.com/trustedsec/ptf/blob/master/modules/exploitation/hconstf.py , the REPOSITORY_LOCATION is hard coded as x86.  When I use this module in my x86_64 system, this module does not work.

I would like the ptf can have two REPOSITORY_LOCATION, one is for x86 and the other is for x86_64.  The ptf can auto-detect your system and install the suitable file automatically.

The ptf also can handle if there is only one generic link in REPOSITORY_LOCATION.

The following are the links of the HconSTF in x86 and x86_64 --

http://sourceforge.net/projects/hconframework/files/HconFramework-Fire/HconSTF_0.5_Prime/HconSTF_v0.5_Linux_x86.tar.bz2

http://sourceforge.net/projects/hconframework/files/HconFramework-Fire/HconSTF_0.5_Prime/HconSTF_v0.5_Prime_Linux_x64.tar.bz2

Thanks.

**Comment by trustedsec** [comment]
I'll be adding x86/x64 support soon.. Will keep this open

**Comment by trustedsec** [comment]
I just pushed version 1.1, check out HconSTF now, it has a X64_LOCATION= and will automatically smart detect a 64 bit platform and install. Thanks for the request, just-rerun PTF to get the options.

**Comment by theDevilsVoice** [comment]
I just cloned the repo.... same error? 


[*] Installing and/or updating: modules/exploitation/hconstf
http://sourceforge.net/projects/hconframework/files/HconFramework-Fire/HconSTF_0.5_Prime/HconSTF_v0.5_Prime_Linux_x64.tar.bz2
[*] Detected an empty folder, purging and re-checking out...
[!] DANGER WILL ROBINSON. DANGER WILL ROBINSON. Error has occured.
[!] It's not possible its due to my coding skillz, it must be you? :-)
[!] Printing that error. Get that error. You get it: [Errno 2] No such file or directory: '/pentest/exploitation/hconstf/'


thedevilsvoice@tdv-laptop ~/workspace/ptf $ cat modules/exploitation/hconstf.py | grep X64_LOCATION=
X64_LOCATION="http://sourceforge.net/projects/hconframework/files/HconFramework-Fire/HconSTF_0.5_Prime/HconSTF_v0.5_Prime_Linux_x64.tar.bz2"
