### ISSUE TITLE
Does ptf expect Python v2.x?

### ISSUE THREAD

**Issue by NetwarSystem** [trustedsec/ptf#575]
I'm not a penetration tester by trade, am just in a role where I have to help some people who are, so I'm trying to get a little less dumb about things.

I have a Burp Suite Pro license and am reading Hands-On Application Penetration Testing With Burp Suite. The person who recommended this described Kali as "annoying" (I heartily agree) and suggested that I just install ptf on whatever Debian based OS I want. Most of my stuff is Ubuntu Budgie 20.04, so I picked an existing investigation oriented VM.

Python is my primary language and the following three line script gets run on every box as part of the initial install:

```
#!/bin/ bash
apt install python3-pip
update-alternatives --install /usr/bin/python python /usr/bin/python3 1
```
I was watching this run:

```
./ptf
use modules/install_update_all
```

and I saw some failures and complaints about pip not being available, so I restarted it under tmux with logging enabled. I see a couple references to Python 2 specific stuff, and there are some mentions of Python 3.7. What comes with Budgie these days is Python 3.8.5. 

Once the install is sorted out, is there a formula for integrating Burp Suite Pro? Or am I misunderstanding the path I should be taking?

**Comment by thejoker3000** [comment]
@NetwarSystem To be honest, Kali is a fantastic pentesting system to use. Alternatively, you have Parrot OS.
As for the **install_update_all**, that's not really what you want to run when in Kali because it will cause conflicts with the tools that are already installed. 
This tool is already compatible, that I can remember, with Python 2.x so it doesn't really rely on python 2.x because it can run with Python 3.x
Also, Burpsuite Pro isn't really something you need until you are like already working as a pentester but everyone can do what they want :)

**Comment by thejoker3000** [comment]
If you have this clear, can you close it?
